version: "2"

services:
  myapp:
    image: "bitnami/symfony:1"
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=symfony
      - MARIADB_PASSWORD=symfony
      - MARIADB_DATABASE=symfony
    depends_on:
      - mariadb
  mariadb:
    image: "bitnami/mariadb:10.3"
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=symfony
      - MARIADB_PASSWORD=symfony
      - MARIADB_DATABASE=symfony
